"""empty message

Revision ID: 06af87c33ecd
Revises: 16de2f28c8a0
Create Date: 2022-05-30 17:41:34.771907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06af87c33ecd'
down_revision = '16de2f28c8a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talents', sa.Column('company', sa.String(length=128), nullable=True))
    op.alter_column('talents', 'current_jobTitle',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('talents', 'current_jobTitle',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('talents', 'company')
    # ### end Alembic commands ###
