"""empty message

Revision ID: 1e2a4f2b03d2
Revises: 4e43c96bb85d
Create Date: 2022-06-10 16:43:46.260858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e2a4f2b03d2'
down_revision = '4e43c96bb85d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobshortlists')
    op.add_column('talents', sa.Column('years_experience', sa.String(length=128), nullable=True))
    op.add_column('talents', sa.Column('education', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talents', 'education')
    op.drop_column('talents', 'years_experience')
    op.create_table('jobshortlists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('talent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='jobshortlists_company_id_fkey'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='jobshortlists_job_id_fkey'),
    sa.ForeignKeyConstraint(['talent_id'], ['users.id'], name='jobshortlists_talent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='jobshortlists_pkey')
    )
    # ### end Alembic commands ###
