"""empty message

Revision ID: 303f47a447cb
Revises: 0d09d22cd2c4
Create Date: 2022-06-07 11:15:43.926418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303f47a447cb'
down_revision = '0d09d22cd2c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('uuid', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'uuid')
    # ### end Alembic commands ###
