"""empty message

Revision ID: 312e349506d6
Revises: 3843c4fbab01
Create Date: 2022-05-31 18:41:40.527157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '312e349506d6'
down_revision = '3843c4fbab01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('v_data', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), nullable=False))
    op.drop_column('videos', 'title')
    op.drop_column('videos', 'duration')
    op.drop_column('videos', 'target_id')
    op.drop_column('videos', 'url')
    op.drop_column('videos', 'sequence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('sequence', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('videos', sa.Column('url', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('videos', sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('duration', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('videos', sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('videos', 'v_data')
    # ### end Alembic commands ###
