"""empty message

Revision ID: 3843c4fbab01
Revises: 36e5daa6f29b
Create Date: 2022-05-31 17:47:07.960869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3843c4fbab01'
down_revision = '36e5daa6f29b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('work_history', postgresql.ARRAY(sa.String(length=128)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'work_history')
    # ### end Alembic commands ###
