"""empty message

Revision ID: 4032a6c2009c
Revises: f62ea5bbde69
Create Date: 2022-06-02 02:11:16.823734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4032a6c2009c'
down_revision = 'f62ea5bbde69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('job_status', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'job_status')
    op.drop_column('jobs', 'description')
    op.drop_column('jobs', 'modified_at')
    op.drop_column('jobs', 'created_at')
    # ### end Alembic commands ###
