"""empty message

Revision ID: 464886181e2b
Revises: 312e349506d6
Create Date: 2022-06-01 06:49:05.299176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464886181e2b'
down_revision = '312e349506d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'phone_number',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'phone_number',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
