"""empty message

Revision ID: 4650477cda72
Revises: 64f22c1f278f
Create Date: 2022-06-02 13:13:40.536809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4650477cda72'
down_revision = '64f22c1f278f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appliedjobs', sa.Column('talent_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'appliedjobs', 'talents', ['talent_id'], ['id'])
    op.create_foreign_key(None, 'appliedjobs', 'jobs', ['job_id'], ['id'])
    op.drop_column('appliedjobs', 'on_shortlist')
    op.create_foreign_key(None, 'jobshortlists', 'talents', ['talent_id'], ['id'])
    op.create_foreign_key(None, 'jobshortlists', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobshortlists', type_='foreignkey')
    op.drop_constraint(None, 'jobshortlists', type_='foreignkey')
    op.add_column('appliedjobs', sa.Column('on_shortlist', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appliedjobs', type_='foreignkey')
    op.drop_constraint(None, 'appliedjobs', type_='foreignkey')
    op.drop_column('appliedjobs', 'talent_id')
    # ### end Alembic commands ###
