"""empty message

Revision ID: 4bd6348d7152
Revises: 74bf8eefcafd
Create Date: 2022-05-27 21:19:36.335310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4bd6348d7152'
down_revision = '74bf8eefcafd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('region', sa.JSON(), nullable=False))
    op.add_column('jobs', sa.Column('experience_year', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('education', sa.String(length=128), nullable=False))
    op.add_column('jobs', sa.Column('salary', sa.String(length=128), nullable=True))
    op.add_column('jobs', sa.Column('roles', postgresql.ARRAY(sa.String(length=128)), nullable=False))
    op.drop_column('jobs', 'status')
    op.drop_column('jobs', 'candidates')
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'post_at')
    op.drop_column('jobs', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('description', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('post_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('candidates', postgresql.ARRAY(sa.VARCHAR(length=128)), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('status', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('jobs', 'roles')
    op.drop_column('jobs', 'salary')
    op.drop_column('jobs', 'education')
    op.drop_column('jobs', 'experience_year')
    op.drop_column('jobs', 'region')
    # ### end Alembic commands ###
