"""empty message

Revision ID: 64f22c1f278f
Revises: d4dc74b1277a
Create Date: 2022-06-02 10:22:33.197873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f22c1f278f'
down_revision = 'd4dc74b1277a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('video', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'video')
    # ### end Alembic commands ###
