"""empty message

Revision ID: 6cc2cdb1c1bb
Revises: 99b7f18c2c0b
Create Date: 2022-06-08 21:25:51.117865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc2cdb1c1bb'
down_revision = '99b7f18c2c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobshortlists', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('jobshortlists', sa.Column('applied_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'jobshortlists', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobshortlists', type_='foreignkey')
    op.drop_column('jobshortlists', 'applied_at')
    op.drop_column('jobshortlists', 'company_id')
    # ### end Alembic commands ###
