"""empty message

Revision ID: 74bf8eefcafd
Revises: f3a41bcf0f09
Create Date: 2022-05-27 19:43:00.592564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74bf8eefcafd'
down_revision = 'f3a41bcf0f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('region', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('phone_number', sa.String(length=128), nullable=False),
    sa.Column('account_manager_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    # ### end Alembic commands ###
