"""empty message

Revision ID: 7d55834eb7c1
Revises: dd622bda2549
Create Date: 2022-05-27 01:43:48.155059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d55834eb7c1'
down_revision = 'dd622bda2549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.Column('duration', sa.String(length=128), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Videos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Videos',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Videos_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('duration', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('sequence', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Videos_pkey')
    )
    op.drop_table('videos')
    # ### end Alembic commands ###
