"""empty message

Revision ID: 99b7f18c2c0b
Revises: 
Create Date: 2022-06-08 07:16:40.104413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99b7f18c2c0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profileviewhistories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('who', sa.Integer(), nullable=False),
    sa.Column('when', sa.DateTime(), nullable=False),
    sa.Column('which', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('verify_code', sa.Integer(), nullable=True),
    sa.Column('register_status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('v_data', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('uuid', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('region', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('phone_number', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('account_manager_name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avator', sa.String(length=256), nullable=True),
    sa.Column('resume', sa.String(length=256), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('video', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('work_history', postgresql.ARRAY(sa.String(length=128)), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('uuid', sa.String(length=128), nullable=True),
    sa.Column('phone_number', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('region', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('current_jobTitle', sa.String(length=128), nullable=True),
    sa.Column('company', sa.String(length=128), nullable=True),
    sa.Column('current_jobDescription', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('region', sa.JSON(), nullable=False),
    sa.Column('experience_year', sa.String(length=128), nullable=False),
    sa.Column('education', sa.String(length=128), nullable=False),
    sa.Column('salary', sa.String(length=128), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('job_status', sa.String(length=128), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String(length=128)), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appliedjobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('talent_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['talent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobshortlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talent_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['talent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobshortlists')
    op.drop_table('appliedjobs')
    op.drop_table('jobs')
    op.drop_table('talents')
    op.drop_table('profiles')
    op.drop_table('companies')
    op.drop_table('videos')
    op.drop_table('users')
    op.drop_table('profileviewhistories')
    # ### end Alembic commands ###
