"""empty message

Revision ID: aca3e09629fb
Revises: c695cb12f720
Create Date: 2022-05-27 21:30:16.943607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca3e09629fb'
down_revision = 'c695cb12f720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('department', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'department')
    # ### end Alembic commands ###
