"""empty message

Revision ID: b2f98a478ff6
Revises: 1e2a4f2b03d2
Create Date: 2022-06-13 10:54:34.010305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2f98a478ff6'
down_revision = '1e2a4f2b03d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profileviewhistories', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profileviewhistories', sa.Column('type', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
