"""empty message

Revision ID: cf82e37ffd87
Revises: 
Create Date: 2022-06-03 19:33:22.937009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf82e37ffd87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('phone_number', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('region', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('current_jobTitle', sa.String(length=128), nullable=True),
    sa.Column('company', sa.String(length=128), nullable=True),
    sa.Column('current_jobDescription', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('appliedjobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appliedjobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('talent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='appliedjobs_company_id_fkey'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='appliedjobs_job_id_fkey'),
    sa.ForeignKeyConstraint(['talent_id'], ['users.id'], name='appliedjobs_talent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='appliedjobs_pkey')
    )
    op.drop_table('talents')
    # ### end Alembic commands ###
