"""empty message

Revision ID: d7e5f3ec4b5a
Revises: eee4afeeab06
Create Date: 2022-05-31 17:34:37.225971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7e5f3ec4b5a'
down_revision = 'eee4afeeab06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('job', postgresql.ARRAY(sa.String(length=128)), nullable=True))
    op.drop_constraint('profiles_job_id_fkey', 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'job_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('profiles_job_id_fkey', 'profiles', 'jobs', ['job_id'], ['id'])
    op.drop_column('profiles', 'job')
    # ### end Alembic commands ###
