"""empty message

Revision ID: ead656e5233c
Revises: 06af87c33ecd
Create Date: 2022-05-30 17:43:07.679129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead656e5233c'
down_revision = '06af87c33ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('talents', 'current_jobDescription',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('talents', 'current_jobDescription',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
