"""empty message

Revision ID: ee90ddb4ed81
Revises: aca3e09629fb
Create Date: 2022-05-27 23:31:39.855664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee90ddb4ed81'
down_revision = 'aca3e09629fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verify_code', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('register_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'register_status')
    op.drop_column('users', 'verify_code')
    # ### end Alembic commands ###
