"""empty message

Revision ID: f3a41bcf0f09
Revises: bf89589049d3
Create Date: 2022-05-27 05:51:25.697189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3a41bcf0f09'
down_revision = 'bf89589049d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('post_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=128), nullable=False),
    sa.Column('candidates', postgresql.ARRAY(sa.String(length=128)), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Jobs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Jobs_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('post_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('candidates', postgresql.ARRAY(sa.VARCHAR(length=128)), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Jobs_pkey')
    )
    op.drop_table('jobs')
    # ### end Alembic commands ###
