"""empty message

Revision ID: faac96d04ebe
Revises: 7d55834eb7c1
Create Date: 2022-05-27 02:17:26.127772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faac96d04ebe'
down_revision = '7d55834eb7c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobshortlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talent_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profileviewhistories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('who', sa.Integer(), nullable=False),
    sa.Column('when', sa.DateTime(), nullable=False),
    sa.Column('which', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profileviewhistories')
    op.drop_table('jobshortlists')
    # ### end Alembic commands ###
