"""empty message

Revision ID: fddf331b1560
Revises: f3a41bcf0f09
Create Date: 2022-05-27 19:39:23.180987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fddf331b1560'
down_revision = 'f3a41bcf0f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('phone_number', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'phone_number')
    # ### end Alembic commands ###
